name: watch_hub_ep
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_database: ^11.3.9
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.0.4
  http: ^1.1.0
  mime: ^2.0.0
  intl: ^0.20.2
  cloud_firestore: ^5.6.11
  go_router: ^13.0.1
  flutter_svg: ^2.2.0
  timeago: ^3.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo.png
    - assets/images/default_user.png
    - assets/fonts/NotoSans-Regular.ttf

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/splash_logo.png
  fullscreen: true

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#0D0D0D"
    color: "#0D0D0D"
